"""add list name column to person_info table and make it nullable

Revision ID: 4fee5ee81c2e
Revises: 690b17b9f427
Create Date: 2026-01-17 12:58:46.155105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fee5ee81c2e'
down_revision = '690b17b9f427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_info', sa.Column('list_name', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person_info', 'list_name')
    # ### end Alembic commands ###
